import localFont from "next/font/local";
import "./globals.css";
import { Montserrat, Anton, Ephesis } from "next/font/google";

const greenos = localFont({
  src: "./fonts/Greenos.ttf",
  variable: "--font-greenos",
  weight: "400 500 600 700 800 900",
});
const moderniz = localFont({
  src: "./fonts/Moderniz.otf",
  variable: "--font-moderniz",
  weight: "400 500 600 700 800 900",
});

const montserrat = Montserrat({ subsets: ["latin"], weight: ["200", "300", "400", "500", "700", "600", "800"], variable: "--font-montserrat" });
const anton = Anton({ subsets: ["latin"], weight: ["400"], variable: "--font-anton" });
const ephesis = Ephesis({ subsets: ["latin"], weight: ["400"], variable: "--font-ephesis" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${ephesis.variable} ${greenos.variable} ${moderniz.variable} ${montserrat.variable} ${anton.variable} font-montserrat antialiased`}>{children}</body>
    </html>
  );
}
